# Generated by Django 5.1.1 on 2025-11-01 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('arquivo', models.FileField(help_text='Arquivo XLSX ou CSV', upload_to='uploads/')),
                ('processado', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Upload',
                'verbose_name_plural': 'Uploads',
                'db_table': 'movie_upload',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(help_text='Arquivo XLSX gerado após o processamento.', upload_to='reports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('upload', models.ForeignKey(help_text='Upload que originou este relatório.', on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='movies.upload')),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('ano', models.CharField(blank=True, max_length=10, null=True)),
                ('elenco', models.TextField(blank=True, null=True)),
                ('sinopse', models.TextField(blank=True, null=True)),
                ('genero', models.CharField(blank=True, max_length=255, null=True)),
                ('diretor', models.CharField(blank=True, max_length=255, null=True)),
                ('nota_imdb', models.CharField(blank=True, max_length=10, null=True)),
                ('nota_metacritic', models.CharField(blank=True, max_length=10, null=True)),
                ('nota_rotten', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('upload', models.ForeignKey(help_text='Arquivo de origem deste conjunto de filmes.', on_delete=django.db.models.deletion.CASCADE, related_name='filmes', to='movies.upload')),
            ],
            options={
                'verbose_name': 'Movie',
                'verbose_name_plural': 'Movies',
                'db_table': 'movie',
                'ordering': ['-created_at'],
            },
        ),
    ]
